### ISSUE TITLE
Cannot run the example

### ISSUE THREAD

**Issue by ramiroaisen** [cztomsik/graffiti#148]
I tried to run the example and I get the following error
```
internal/validators.js:112
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Module.require (internal/modules/cjs/loader.js:841:3)
    at require (internal/modules/cjs/helpers.js:74:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:116:20)
    at Object.runInThisContext (vm.js:306:38)
    at Object.<anonymous> ([eval]-wrapper:9:26)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at evalScript (internal/process/execution.js:80:25)
    at internal/main/eval_string.js:23:3
```
Im running in fedora 29

**Comment by cztomsik** [comment]
Sorry, I made mistake when fixing windows.
Should be fine now (tested on linux, win & mac)
